add_sample(day01 2016)
copy_single_input_file(2016_day01 day01.example2)
add_sample(day02 2016)
add_sample(day03 2016)
add_sample(day04 2016)
add_sample(day05 2016)
target_link_libraries(2016_day05 PRIVATE md5)
add_sample(day06 2016)
add_sample(day07 2016)
copy_single_input_file(2016_day07 day07.example2)
